/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

angular.module('UberAPILib')
    .factory('Configuration', [Configuration]);

    function Configuration() {
        return {
            //The base Uri for API calls
            BASEURI : 'https://api.uber.com/v1',

            //OAuth 2.0 Access Token
            //TODO: Replace the oAuthAccessToken with an appropriate value
            oAuthAccessToken : 'TODO: Replace'

        };
    }

}(angular));
