/**
  * UberAPILib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';
angular.module('UberAPILib')
    .factory('ModelFactory', ['ProductCollection',
        'PriceEsitmate',
        'RequestBody',
        'RequestDetailsCollections',
        'Product',
        'Request',
        'UserProfile',
        'Driver',
        'TimeEstimate',
        'Vehicle',
        'UserActivity',
        'Errors',
        'History',
        'PromotionsResponse',
        'Location',
        'RequestMapResponse',
        'SurgeConfirmation',
        'Meta',
        'ErrorBase',
        'TimeEstimateCollection',
        'PriceEstimateCollection',
        ModelFactory]);

	/**
	 * Factory service to create instances of models and exception classes
	 */
    function ModelFactory(ProductCollection,
        PriceEsitmate,
        RequestBody,
        RequestDetailsCollections,
        Product,
        Request,
        UserProfile,
        Driver,
        TimeEstimate,
        Vehicle,
        UserActivity,
        Errors,
        History,
        PromotionsResponse,
        Location,
        RequestMapResponse,
        SurgeConfirmation,
        Meta,
        ErrorBase,
        TimeEstimateCollection,
        PriceEstimateCollection) {

		var classMap = {
            ProductCollection: ProductCollection,
            PriceEsitmate: PriceEsitmate,
            RequestBody: RequestBody,
            RequestDetailsCollections: RequestDetailsCollections,
            Product: Product,
            Request: Request,
            UserProfile: UserProfile,
            Driver: Driver,
            TimeEstimate: TimeEstimate,
            Vehicle: Vehicle,
            UserActivity: UserActivity,
            Errors: Errors,
            History: History,
            PromotionsResponse: PromotionsResponse,
            Location: Location,
            RequestMapResponse: RequestMapResponse,
            SurgeConfirmation: SurgeConfirmation,
            Meta: Meta,
            ErrorBase: ErrorBase,
            TimeEstimateCollection: TimeEstimateCollection,
            PriceEstimateCollection: PriceEstimateCollection
		};

		return {
		    /**
		     * Creates instance of a model class
		     * @param  modelName  {string}  Name of class to instantiate
		     * @returns  {object} Instance of the model class
		     */
			getInstance: function(modelName) {
        		return new classMap[modelName]();
			}
		};
	}

}(angular));
