/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of TimeEstimateCollection
 *
 * @constructor
 */
angular.module('UberAPILib')
    .factory('TimeEstimateCollection', ['BaseModel', TimeEstimateCollectionModel]);

    function TimeEstimateCollectionModel(BaseModel) {
        var TimeEstimateCollection = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.times = this.getValue(obj.times);
        };

        TimeEstimateCollection.prototype = new BaseModel();
        TimeEstimateCollection.prototype.constructor = TimeEstimateCollection;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        TimeEstimateCollection.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'times', realName: 'times', array: true, type: 'TimeEstimate' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        TimeEstimateCollection.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * List of time estimates
         *
         * @return {array}
         */
        TimeEstimateCollection.prototype.getTimes = function () {
            return this.times;
        };
    
        /**
         * Setter for Times
         * 
         * @param {array} value 
         */
        TimeEstimateCollection.prototype.setTimes = function (value) {
            this.times = value;
        };
    
        return TimeEstimateCollection;
    }

}(angular));
